# Generated by Django 5.0 on 2023-12-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="platform",
            field=models.CharField(
                choices=[
                    ("pc", "PC"),
                    ("playstation", "PlayStation"),
                    ("xbox", "Xbox"),
                    ("nintendo", "Nintendo"),
                    ("mac", "Mac"),
                    ("linux", "Linux"),
                    ("android", "Android"),
                    ("ios", "iOS"),
                    ("web", "Web"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
