# Generated by Django 5.0 on 2023-12-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_game_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameDeveloper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("founded_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
